.IFNDEF __CONTROLLER_NONE_ASM__
.DEFINE __CONTROLLER_NONE_ASM__

.SECTION "Controller None" FREE

.DSTRUCT Controller_None_State INSTANCEOF sState VALUES
.ENDST

.ENDS

.ENDIF  ;__CONTROLLER_NONE_ASM__